export default {
  t_1: 'Social responsability',
  m_1: 'Corporate Social Responsibility is the ethical management of a company that seeks coherence between economic growth, cultural support, social equity and environmental care of a particular place. In the mining industry, this is the key to the communion of companies with communities.',
  t_2: 'Why it is necessary?',
  m_2: 'It is nothing new to say that Social Responsibility is an added value, but also an obligation for mining companies, which are constantly in tension with communities or villages in which an excavation project is based.\nThrough this activity, mining companies actively contribute to the development of the local capacities with which they live, with the protection of the environment, with respect for cultural identities and with social values, as well as with the construction of relations of trust and with the strengthening of a culture of dialogue and peace.',
  t_3: 'The end of these practices',
  m_3: 'It is to seek the sustainable development of the villages where companies operate, through the social contribution of mining.\nIt also provides opportunities for the population to access various goods and services. By covering their need for electricity, it makes it possible to connect remote populations to this service and to demand the help of The work generates direct and indirect employment, through the demand for goods and services that comes from the workers and the mining company. Provides education and health, complementing the services provided by the State.',
  ttt_1: 'Mining susteinable',
  mmm_1: 'It is the development that meets the current needs of people without compromising the ability of future generations to meet theirs. The impact generated by mining on the environment is not synonymous with pollution since it can be prevented using modern technology and implementing environmental management and social responsibility programs.',
  tt_1: 'Environmental',
  tt_2: 'Social',
  tt_3: 'Economic',
  mm_1: 'Mining and environmental legislation\nRespect for the environment\nRigorous environmental studies\nNational and International Standards\nSystem environmental management',
  banner_tittle_one: {
    primary: 'Mining with responsability',
    secondary: 'bar foo english'
  },
  banner_tittle_two: {
    primary: 'foo foo english',
    secondary: 'bar foo english'
  },
  banner_tittle_tree: {
    primary: 'foo foo english',
    secondary: 'bar foo english'
  },
  read_more: 'Read more',
  error: {
    problem: 'A problem has occurred',
    wrong_try_again: 'Something went wrong! Please try again.',
    many_person: 'More than one person has been detected, try with an image where you can see only!',
    face_no_detect: 'No face was detected!',
    data_invalid: 'Some data are invalids!'
  },
  success: {
    data_complet: 'Your data was processed correctly!'
  },
  img: {
    has_to_weight: 'The image has to weigh less than {size} Mb',
    only_can_select: '¡Only can select image file!'
  },
  responsability: 'responsability',
  home: 'home',
  sustainable: 'sustainable',
  suggestions: 'suggestions',
  correct: 'Correct',
  test: 'test',
  about: 'about',
  upload_img: 'upload image',
  how: 'how it works?',
  show_my_result: 'Show my results',
  name: 'name',
  age: 'age',
  anger: 'anger',
  contempt: 'contempt',
  disgust: 'disgust',
  fear: 'fear',
  happiness: 'happiness',
  neutral: 'neutral',
  sadness: 'sadness',
  surprise: 'surprise',
  female: 'female',
  male: 'male',
  evaluation: 'evaluation',
  indications: 'indications',
  information: 'information',
  evaluation_text: {
    indication_1: 'Read each question carefully. It should only be marked within the squares of the options that have been chosen. <br>Do not forget that the answers must be honest to obtain a better result.',
    info_1: 'In the following form you must indicate the events that have happened recently.'
  },
  important: 'Important',
  indicate_data: 'Indicate your data',
  indicate_stress_event: 'Choose events',
  form: 'Form',
  questions: {
    death: 'Death of a relative recently',
    changes: 'Aggravation of the health of a family member recently',
    pregnant: 'New member in the family',
    work: 'Having been fired from his job',
    retired: 'It has retired',
    loss: 'Loss of valuables in the event of a disaster or theft',
    debt: 'You have an economic debt',
    low: 'low',
    medium: 'medium',
    hight: 'hight'
  }
}
